### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by abbgrade** [robertkrimen/godocdown#1]
On Ubuntu 12.10 with Go installed via (http://ppa.launchpad.net/gophers/go/ubuntu)

The installation failed:

> sudo go get github.com/robertkrimen/godocdown/godocdown
> /usr/lib/go/src/pkg/github.com/robertkrimen/godocdown/godocdown/dbg.go:8: undefined: dbg.Dbg

**Comment by robertkrimen** [comment]
Thanks for the report.
